### PR TITLE
Directory Separator Fix for Unit Tests

### PR DESCRIPTION
**Pull request by mapthegod**
Replaced static Unix-Style Directory Seperators with dynamic ones from PHPs DIRECTORY_SEPARATOR Constant
Previously all phpunit tests would fail on Windows Machines

### CODE REVIEW

**Comment by pmjones** [comment]
Looking at these, would it be easer/more-readable to instead do a str_replace('/', DIRECTORY_SEPARATOR, $path) at comparison time?

**Comment by mapthegod** [comment]
@pmjones You're right, this way it is much more readable.

**Comment by pmjones** [comment]
Right on.  Can you issue a second pull request on Aura.Framework using that technique?

**Comment by mapthegod** [comment]
Will do for the changes in InflectTest.php.
For those in SystemTest.php I would need to use regular expressions because of the "vfs://", that would in my opinion make the code less readable instead of better.

**Comment by pmjones** [comment]
Sounds reasonable. Thanks!

**Comment by mapthegod** [comment]
@pmjones I think you forgot to merge ;) 
Or did I forget something ?

**Comment by harikt** [comment]
@mapthegod  it seems @pmjones forgot to merge. He is on vacation and will merge once he is back. 

Thanks for the reminder.

**Pull request merged**
